---
title: "My Final Project"
author: "Rachel Aliwalas and Lillian Fok"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

```{r, include=FALSE}
library(tidyverse)
library(patchwork)
library(janitor)
library(readr)
library(lubridate)
```


<!--
Comments in HTML are like this! 
-->


```{r, include=FALSE}
artistDf <- read_csv("BillboardFromLast20/artistDf.csv") %>% clean_names()
billboardHot100 <- read_csv("BillboardFromLast20/billboardHot100_1999-2019.csv") %>% clean_names()
songAttributes <- read_csv("BillboardFromLast20/songAttributes_1999-2019.csv") %>% clean_names()
spotify_weekly_streams <- read_csv("BillboardFromLast20/spotifyWeeklyTop200Streams.csv") %>% clean_names()
```


```{r, include=FALSE}
clean_spotify <- spotify_weekly_streams %>% 
  separate(week, into = c("year","month","day"), sep = "-") %>% 
  select(-x1, -features) %>% 
  mutate(day = as.character(day),
         week = ifelse(day == "01"| day == "02"| day == "03" | day == "04"|  day == "05" | day == "06" | day == "07", "1", 
                       ifelse(day == "08"|day == "09" | day == "10"| day == "11" | day == "12" |  day == "13" | day == "14", "2",
                       ifelse(day == "15"| day == "16" | day == "17"| day == "18" |  day == "19" |  day == "20" | day == "21", "3", 
                       ifelse(day == "22"| day == "23" | day == "24"| day == "25" |  day == "26" |  day == "27" | day == "28", "4",
                       "5")))))

bill100 <- billboardHot100 %>% 
  separate(week, into = c("year","month","day"), sep = "-") %>% 
  select(-x1, -writing_credits, -lyrics, -date, -features, -artists) %>% 
  filter(year == "2016" | year == "2017" | year == "2018" | year == "2019") %>% 
  mutate(day = as.character(day),
       week = ifelse(day == "01"| day == "02"| day == "03" | day == "04"|  day == "05" | day == "06" | day == "07", "1", 
                      ifelse(day == "08"|day == "09" | day == "10"| day == "11" | day == "12" |  day == "13" | day == "14", "2",
                       ifelse(day == "15"| day == "16" | day == "17"| day == "18" |  day == "19" |  day == "20" | day == "21", "3", 
                       ifelse(day == "22"| day == "23" | day == "24"| day == "25" |  day == "26" |  day == "27" | day == "28", "4",
                       "5")))))
  
```



```{r, include=FALSE}
test <- bill100 %>%
  full_join(clean_spotify, by = c("year", "month", "name")) %>% 
  filter(!is.na(streams), !is.na(peak_position)) %>% 
  select(-day.x, -day.y, -genre) %>% 
  group_by(name) %>% 
  mutate(total = sum(streams)) %>% 
  mutate(per_hundred_thousand = total/100000)

```


```{r, include=FALSE}
total_streams <- bill100 %>%
  left_join(clean_spotify, by = c("year", "month", "week", "name")) %>% 
  filter(!is.na(streams)) %>% 
  select(-day.x,-day.y) %>% 
  group_by(name) %>% 
  summarise(total = sum(streams)) %>% 
  mutate(per_hundred_thousand = total/100000) %>% 
  arrange(desc(per_hundred_thousand)) %>% 
  slice(1:20)
```


```{r}
total_streams10 <- total_streams %>%   arrange(desc(per_hundred_thousand)) %>% 
  slice(1:10)

try <- total_streams10 %>% left_join(bill100, by = "name") %>% 
  select(-genre) %>% 
  filter(!is.na(peak_position)) %>% 
  group_by(name, per_hundred_thousand) %>% 
  summarise(m_pos = min(peak_position))


```


```{r}
ggplot(try, aes(y = per_hundred_thousand, x = m_pos, color = name)) + 
  geom_point(size = 2.5) + 
  scale_x_reverse() +
  geom_text(aes(label = ifelse(name == "God's Plan" | name == "Unforgettable", as.character(name),''), hjust=1, vjust=1)) +
  labs(title = "Billboard's Top 100 Peak Postitioning and Total Streams (2016-2019)", x = "Peak Billboard 100 Position", y = "Spotify Streams (Per 100,000 Thousand)")
```



```{r}
ggplot(data = total_streams, aes(x = name, y = per_hundred_thousand)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + labs(title = "20 Most Streamed Songs from 2016-2019", y = "Total Streams (per 100,000)", x = "Song Title")

```


# SECTION NAME

## Subsection name

Write an intro `index.html` page in blog-post style that summarizes your work. It should have

1. One visualization that best summarizes your work.
1. No more than 200 words of text

```{r, echo = FALSE}

```


